#!/usr/bin/env python3
"""Serve a static PDF site and maintain branch/timestamp version metadata."""

from __future__ import annotations

import argparse
import functools
import hashlib
import http.server
import json
import os
import socketserver
import subprocess
import threading
import time
import urllib.parse
from pathlib import Path


DEFAULT_PAGES_URL = "https://kimpossible-ty.github.io/Partial-Differential-Equations"
DEFAULT_SOURCE_BASE_URL = "https://github.com/kimpossible-TY/Partial-Differential-Equations/tree"


def git_value(root: Path, *args: str, fallback: str) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(root), *args],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return fallback


def current_branch(root: Path) -> str:
    if os.environ.get("GITHUB_REF_NAME"):
        return os.environ["GITHUB_REF_NAME"]
    return git_value(root, "branch", "--show-current", fallback="local") or "local"


def iso_now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def pdf_info(root: Path, pdf_name: str) -> tuple[str, int]:
    pdf_path = root / pdf_name
    if not pdf_path.exists():
        return "", 0

    digest = hashlib.sha256()
    with pdf_path.open("rb") as pdf_file:
        for chunk in iter(lambda: pdf_file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest(), pdf_path.stat().st_size


def write_version_files(root: Path, built_at: str | None = None, pdf_name: str = "main.pdf") -> str:
    built_at = built_at or os.environ.get("PDF_BUILD_AT") or iso_now()
    branch = current_branch(root)
    version_id = f"{branch}@{built_at}"
    pages_url = os.environ.get("PDE_PAGES_URL", DEFAULT_PAGES_URL).rstrip("/")
    source_base_url = os.environ.get("PDF_SOURCE_BASE_URL", DEFAULT_SOURCE_BASE_URL).rstrip("/")
    source_ref = git_value(root, "rev-parse", "HEAD", fallback=branch)
    pdf_sha256, pdf_size = pdf_info(root, pdf_name)

    query = urllib.parse.urlencode({"pdfBranch": branch, "pdfBuiltAt": built_at})
    (root / "build-info.typ").write_text(
        "\n".join(
            [
                "// Generated by pdf-versioning.",
                f'#let document-branch = "{branch}"',
                f'#let document-built-at = "{built_at}"',
                f'#let document-version-id = "{version_id}"',
                f'#let document-base-url = "{pages_url}"',
                f'#let document-version-check-url = "{pages_url}/?{query}"',
                f'#let document-pdf-url = "{pages_url}/{pdf_name}"',
                f'#let document-source-url = "{source_base_url}/{source_ref}"',
                "",
            ]
        ),
        encoding="utf-8",
    )

    (root / "version.json").write_text(
        json.dumps(
            {
                "branch": branch,
                "builtAt": built_at,
                "versionId": version_id,
                "pdfSha256": pdf_sha256,
                "pdfSize": pdf_size,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return version_id


def ensure_browser_helper(root: Path) -> None:
    target = root / "pdf-version-check.js"
    if target.exists():
        return

    source = Path(__file__).resolve().with_name("pdf-version-check.js")
    target.write_text(source.read_text(encoding="utf-8"), encoding="utf-8")
    print(f"Initialized browser helper: {target.name}", flush=True)


def ensure_version_files(root: Path, pdf_name: str) -> None:
    ensure_browser_helper(root)
    if not (root / "build-info.typ").exists() or not (root / "version.json").exists():
        version_id = write_version_files(root, pdf_name=pdf_name)
        print(f"Initialized version metadata: {version_id}", flush=True)


def typst_mtime_snapshot(root: Path) -> dict[Path, int]:
    ignored_parts = {".git", ".venv", "typst-packages"}
    snapshot: dict[Path, int] = {}
    for path in root.rglob("*.typ"):
        if ignored_parts.intersection(path.relative_to(root).parts):
            continue
        if path.name == "build-info.typ":
            continue
        snapshot[path] = path.stat().st_mtime_ns
    return snapshot


def watch_typst_versions(root: Path, interval: float, pdf_name: str) -> None:
    ensure_version_files(root, pdf_name)
    snapshot = typst_mtime_snapshot(root)
    while True:
        time.sleep(interval)
        next_snapshot = typst_mtime_snapshot(root)
        if next_snapshot != snapshot:
            version_id = write_version_files(root, pdf_name=pdf_name)
            print(f"Updated version metadata: {version_id}", flush=True)
            snapshot = next_snapshot


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Serve a PDF site and manage version metadata")
    parser.add_argument("--host", default="0.0.0.0", help="Host interface to bind")
    parser.add_argument("--port", type=int, default=8000, help="Port to bind")
    parser.add_argument("--directory", "--root", dest="directory", default=".", help="Project root to serve")
    parser.add_argument("--pdf-name", default="main.pdf", help="Published PDF filename")
    parser.add_argument("--watch-version", action="store_true", help="Update metadata whenever Typst sources change")
    parser.add_argument("--watch-interval", type=float, default=1.0, help="Typst source polling interval")
    parser.add_argument("--write-version-once", action="store_true", help="Write metadata once, then exit")
    parser.add_argument("--ensure-version-files", action="store_true", help="Create metadata only when missing, then exit")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    serve_dir = Path(args.directory).expanduser().resolve()

    if not serve_dir.exists() or not serve_dir.is_dir():
        raise SystemExit(f"Invalid directory: {serve_dir}")

    if args.ensure_version_files:
        ensure_version_files(serve_dir, args.pdf_name)
        return

    if args.write_version_once:
        ensure_browser_helper(serve_dir)
        print(write_version_files(serve_dir, pdf_name=args.pdf_name))
        return

    if args.watch_version:
        watcher = threading.Thread(
            target=watch_typst_versions,
            args=(serve_dir, args.watch_interval, args.pdf_name),
            daemon=True,
        )
        watcher.start()

    handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory=str(serve_dir))

    with socketserver.TCPServer((args.host, args.port), handler) as httpd:
        print(f"Serving {serve_dir} on http://{args.host}:{args.port}")
        print("Press Ctrl+C to stop")
        httpd.serve_forever()


if __name__ == "__main__":
    main()
