[package]
name = "project-references"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Kim Taeyoung"]
license = "MIT"
description = "Cross-project global references using the source project's reference rules."
